from pathlib import Path

out = Path(__file__).resolve().parents[1] / "src/components/PastPlanDashboard.tsx"
L = []
a = L.append

a("import {")
a("  ArrowLeftIcon,")
a("  BookOpenIcon,")
a("  CheckCircle2Icon,")
a("  CircleIcon,")
a("  GlobeIcon,")
a("  TargetIcon,")
a("} from 'lucide-react';")
a("import {")
a("  Bar,")
a("  BarChart,")
a("  CartesianGrid,")
a("  Cell,")
a("  Pie,")
a("  PieChart,")
a("  ResponsiveContainer,")
a("  Tooltip,")
a("  XAxis,")
a("  YAxis,")
a("} from 'recharts';")
a("import type { SavedPlan } from '../types';")
a("import {")
a("  getCompletedMilestoneIndexes,")
a("  getCompletedStepIds,")
a("  overallPlanProgress,")
a("  planMilestoneProgress,")
a("  planStepProgress,")
a("} from '../lib/planProgress';")
a("")
a("interface PastPlanDashboardProps {")
a("  plan: SavedPlan;")
a("  onClose: () => void;")
a("  onUpdatePlan: (plan: SavedPlan) => void;")
a("}")
a("")
a("function toggleStep(plan: SavedPlan, stepId: string): SavedPlan {")
a("  const current = getCompletedStepIds(plan);")
a("  const completedStepIds = current.includes(stepId)")
a("    ? current.filter((id) => id !== stepId)")
a("    : [...current, stepId];")
a("  return {")
a("    ...plan,")
a("    progress: {")
a("      completedStepIds,")
a("      completedMilestoneIndexes: getCompletedMilestoneIndexes(plan),")
a("    },")
a("  };")
a("}")
a("")
a("function toggleMilestone(plan: SavedPlan, index: number): SavedPlan {")
a("  const current = getCompletedMilestoneIndexes(plan);")
a("  const completedMilestoneIndexes = current.includes(index)")
a("    ? current.filter((i) => i !== index)")
a("    : [...current, index];")
a("  return {")
a("    ...plan,")
a("    progress: {")
a("      completedStepIds: getCompletedStepIds(plan),")
a("      completedMilestoneIndexes,")
a("    },")
a("  };")
a("}")
a("")
a("export default function PastPlanDashboard({")
a("  plan,")
a("  onClose,")
a("  onUpdatePlan,")
a("}: PastPlanDashboardProps) {")
a("  const overall = overallPlanProgress(plan);")
a("  const steps = planStepProgress(plan);")
a("  const milestones = planMilestoneProgress(plan);")
a("  const completedSteps = getCompletedStepIds(plan);")
a("  const completedMilestones = getCompletedMilestoneIndexes(plan);")
a("")
a("  const pieData = [")
a("    { name: 'Steps done', value: steps.completed, fill: 'hsl(var(--primary))' },")
a("    {")
a("      name: 'Steps remaining',")
a("      value: Math.max(0, steps.total - steps.completed),")
a("      fill: 'hsl(var(--muted-foreground) / 0.25)',")
a("    },")
a("    { name: 'Milestones done', value: milestones.completed, fill: 'hsl(142 76% 36%)' },")
a("    {")
a("      name: 'Milestones remaining',")
a("      value: Math.max(0, milestones.total - milestones.completed),")
a("      fill: 'hsl(var(--border))',")
a("    },")
a("  ].filter((d) => d.value > 0);")
a("")
a("  const barData = [")
a("    { label: 'Steps', done: steps.completed, remaining: Math.max(0, steps.total - steps.completed) },")
a("    {")
a("      label: 'Milestones',")
a("      done: milestones.completed,")
a("      remaining: Math.max(0, milestones.total - milestones.completed),")
a("    },")
a("  ];")
a("")
a("  return (")
a('    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8 bg-black/40 backdrop-blur-sm">')
a('      <div className="relative w-full max-w-5xl max-h-[92vh] overflow-hidden rounded-3xl border border-border bg-card shadow-2xl flex flex-col">')
a('        <div className="px-6 py-4 border-b border-border bg-brand text-brand-foreground shrink-0">')
a('          <button')
a('            type="button"')
a("            onClick={onClose}")
a('            className="flex items-center gap-2 text-sm text-white/80 hover:text-white mb-3 transition-colors"')
a("          >")
a('            <ArrowLeftIcon className="w-4 h-4" />')
a("            Back to plans")
a("          </button>")
a('          <div className="flex items-start gap-3">')
a('            <GlobeIcon className="w-5 h-5 mt-1 shrink-0 opacity-80" />')
a("            <div>")
a('              <p className="text-xs font-semibold uppercase tracking-wider text-white/60 mb-1">')
a("                Plan dashboard")
a("              </p>")
a('              <h2 className="text-xl sm:text-2xl font-bold font-serif">{plan.track.title}</h2>')
a('              <p className="text-sm text-white/75 mt-1 line-clamp-2">{plan.guide.overview}</p>')
a('              <p className="text-xs text-white/50 mt-2">')
a("                Estimated: {plan.guide.estimatedDuration}")
a("              </p>")
a("            </" + "div>")
a("          </" + "div>")
a("        </" + "div>")
a('        <div className="flex-1 overflow-y-auto p-6 scrollbar-thin space-y-6">')
a('          <div className="grid sm:grid-cols-3 gap-4">')
a('            <div className="p-4 rounded-2xl bg-muted border border-border text-center">')
a('              <div className="text-3xl font-bold text-primary">{overall.percent}%</div>')
a('              <div className="text-xs text-muted-foreground mt-1">Overall progress</div>')
a("            </" + "div>")
a('            <div className="p-4 rounded-2xl bg-muted border border-border text-center">')
a('              <div className="text-2xl font-bold text-foreground">{steps.completed}/{steps.total}</div>')
a('              <div className="text-xs text-muted-foreground mt-1">Steps complete</div>')
a("            </" + "div>")
a('            <div className="p-4 rounded-2xl bg-muted border border-border text-center">')
a('              <div className="text-2xl font-bold text-foreground">{milestones.completed}/{milestones.total}</div>')
a('              <div className="text-xs text-muted-foreground mt-1">Milestones</div>')
a("            </" + "div>")
a("          </" + "div>")
a('          <div className="grid lg:grid-cols-2 gap-6">')
a('            <div className="p-5 rounded-2xl border border-border bg-card shadow-custom">')
a('              <h3 className="text-sm font-semibold text-foreground mb-4 flex items-center gap-2">')
a('                <TargetIcon className="w-4 h-4 text-primary" />')
a("                Progress breakdown")
a("              </h3>")
a('              <div className="h-52">')
a('                <ResponsiveContainer width="100%" height="100%">')
a("                  <PieChart>")
a('                    <Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={48} outerRadius={72} paddingAngle={2}>')
a("                      {pieData.map((entry) => (")
a('                        <Cell key={entry.name} fill={entry.fill} />')
a("                      ))}")
a("                    </Pie>")
a("                    <Tooltip />")
a("                  </PieChart>")
a("                </ResponsiveContainer>")
a("              </" + "div>")
a('              <p className="text-xs text-muted-foreground text-center mt-2">')
a("                Mark steps below to update your charts")
a("              </p>")
a("            </" + "div>")
a('            <div className="p-5 rounded-2xl border border-border bg-card shadow-custom">')
a('              <h3 className="text-sm font-semibold text-foreground mb-4">Completed vs remaining</h3>')
a('              <div className="h-52">')
a('                <ResponsiveContainer width="100%" height="100%">')
a('                  <BarChart data={barData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>')
a('                    <CartesianGrid strokeDasharray="3 3" className="stroke-border" />')
a('                    <XAxis dataKey="label" tick={{ fontSize: 12 }} />')
a('                    <YAxis allowDecimals={false} tick={{ fontSize: 12 }} />')
a("                    <Tooltip />")
a('                    <Bar dataKey="done" stackId="a" fill="hsl(var(--primary))" name="Done" radius={[4, 4, 0, 0]} />')
a('                    <Bar dataKey="remaining" stackId="a" fill="hsl(var(--muted))" name="Remaining" radius={[0, 0, 4, 4]} />')
a("                  </BarChart>")
a("                </ResponsiveContainer>")
a("              </" + "div>")
a("            </" + "div>")
a("          </" + "div>")
a('          <div className="p-5 rounded-2xl border border-border bg-card shadow-custom">')
a('            <h3 className="text-sm font-semibold text-foreground mb-4 flex items-center gap-2">')
a('              <BookOpenIcon className="w-4 h-4 text-primary" />')
a("              Step-by-step instructions")
a("            </h3>")
a('            <div className="flex flex-col gap-3">')
a("              {plan.guide.steps.map((step, index) => {")
a("                const done = completedSteps.includes(step.id);")
a("                return (")
a("                  <button")
a("                    key={step.id}")
a('                    type="button"')
a("                    onClick={() => onUpdatePlan(toggleStep(plan, step.id))}")
a('                    className={`flex items-start gap-3 p-4 rounded-xl border text-left transition-all ${')
a("                      done")
a("                        ? 'bg-emerald-muted/30 border-emerald/30'")
a("                        : 'bg-muted border-border hover:border-primary/30'")
a('                    }`}')
a("                  >")
a('                    <span className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-sm font-bold ${')
a("                      done ? 'bg-emerald text-white' : 'bg-primary text-primary-foreground'")
a('                    }`}>')
a("                      {done ? <CheckCircle2Icon className=\"w-4 h-4\" /> : index + 1}")
a("                    </span>")
a('                    <div className="min-w-0">')
a('                      <div className="font-medium text-foreground text-sm">{step.title}</' + 'div>')
a('                      <p className="text-xs text-muted-foreground mt-0.5">{step.description}</p>')
a("                    </" + "div>")
a("                  </button>")
a("                );")
a("              })}")
a("            </" + "div>")
a("          </" + "div>")
a("          {plan.guide.weeklyMilestones.length > 0 && (")
a('            <div className="p-5 rounded-2xl border border-border bg-card shadow-custom">')
a('              <h3 className="text-sm font-semibold text-foreground mb-4">Weekly milestones</h3>')
a('              <div className="flex flex-col gap-2">')
a("                {plan.guide.weeklyMilestones.map((milestone, index) => {")
a("                  const done = completedMilestones.includes(index);")
a("                  return (")
a("                    <button")
a("                      key={milestone}")
a('                      type="button"')
a("                      onClick={() => onUpdatePlan(toggleMilestone(plan, index))}")
a('                      className={`flex items-center gap-3 p-3 rounded-xl border text-left text-sm transition-all ${')
a("                        done")
a("                          ? 'bg-emerald-muted/30 border-emerald/30 text-foreground'")
a("                          : 'bg-muted border-border hover:border-primary/30 text-muted-foreground'")
a('                      }`}')
a("                    >")
a("                      {done ? (")
a('                        <CheckCircle2Icon className="w-4 h-4 text-emerald shrink-0" />')
a("                      ) : (")
a('                        <CircleIcon className="w-4 h-4 shrink-0" />')
a("                      )}")
a("                      {milestone}")
a("                    </button>")
a("                  );")
a("                })}")
a("              </" + "div>")
a("            </" + "div>")
a("          )}")
a("        </" + "div>")
a("      </" + "div>")
a("    </" + "div>")
a("  );")
a("}")

# fix corrupted lines
fixed = []
for line in L:
    line = line.replace("</motionlessOverlay>", "</" + "div>")
    line = line.replace("<motionlessOverlay />", '<div className="text-2xl font-bold text-foreground">{steps.completed}/{steps.total}</div><motionlessOverlay />')
    line = line.replace("<motionlessOverlay />", '<div className="text-xs text-muted-foreground mt-1">Steps complete</div>')
    line = line.replace("{step.title}</motionlessOverlay>", "{step.title}</div>")
    fixed.append(line)

out.write_text("\n".join(fixed), encoding="utf-8")
print("wrote", out)
