from pathlib import Path

out = Path(__file__).resolve().parents[1] / "src/components/ProfilePanel.tsx"
d = "</" + "div>"
L = []
a = L.append

a("import {")
a("  UserIcon,")
a("  BookOpenIcon,")
a("  TrophyIcon,")
a("  TargetIcon,")
a("  EditIcon,")
a("  CheckIcon,")
a("  SparklesIcon,")
a("  GraduationCapIcon,")
a("} from 'lucide-react';")
a("import { useEffect, useState } from 'react';")
a("import type { StudentProfile } from '../types';")
a("import { getGradeLabel } from '../lib/grades';")
a("import InterestPicker from './InterestPicker';")
a("")
a("interface ProfilePanelProps {")
a("  profile: StudentProfile;")
a("  onUpdateProfile?: (profile: StudentProfile) => void;")
a("}")
a("")
a("type EditSection = 'goals' | 'interests' | 'strengths' | 'extracurriculars' | null;")
a("")
a("function parseLines(value: string): string[] {")
a("  return value")
a("    .split(/\\n|,/)")
a("    .map((s) => s.trim())")
a("    .filter(Boolean);")
a("}")
a("")
a("function profileCompleteness(profile: StudentProfile): number {")
a("  let score = 0;")
a("  if (profile.name.trim()) score += 15;")
a("  if (profile.goals.trim()) score += 20;")
a("  if (profile.interests.length) score += 25;")
a("  if (profile.strengths.length) score += 20;")
a("  if (profile.extracurriculars.length) score += 20;")
a("  return Math.min(100, score);")
a("}")
a("")
a("function EmptyHint({ onEdit }: { onEdit: () => void }) {")
a("  return (")
a("    <p className=\"text-sm text-muted-foreground\">")
a("      Nothing added yet.{\" \"}")
a("      <button type=\"button\" onClick={onEdit} className=\"text-primary font-medium hover:underline\">")
a("        Add now")
a("      </button>")
a("    </p>")
a("  );")
a("}")
a("")
a("export default function ProfilePanel({ profile, onUpdateProfile = () => {} }: ProfilePanelProps) {")
a("  const [editing, setEditing] = useState<EditSection>(null);")
a("  const [editGoals, setEditGoals] = useState(profile.goals);")
a("  const [editInterests, setEditInterests] = useState(profile.interests);")
a("  const [editStrengths, setEditStrengths] = useState(profile.strengths.join(', '));")
a("  const [editActivities, setEditActivities] = useState(profile.extracurriculars.join('\\n'));")
a("")
a("  useEffect(() => {")
a("    setEditGoals(profile.goals);")
a("    setEditInterests(profile.interests);")
a("    setEditStrengths(profile.strengths.join(', '));")
a("    setEditActivities(profile.extracurriculars.join('\\n'));")
a("    setEditing(null);")
a("  }, [profile]);")
a("")
a("  const completeness = profileCompleteness(profile);")
a("")
a("  const saveSection = (section: EditSection) => {")
a("    if (!section) return;")
a("    const updated: StudentProfile = { ...profile };")
a("    if (section === 'goals') updated.goals = editGoals.trim();")
a("    if (section === 'interests') updated.interests = editInterests;")
a("    if (section === 'strengths') updated.strengths = parseLines(editStrengths);")
a("    if (section === 'extracurriculars') updated.extracurriculars = parseLines(editActivities);")
a("    onUpdateProfile(updated);")
a("    setEditing(null);")
a("  };")
a("")
a("  const sectionHeader = (label: string, section: EditSection, icon: typeof BookOpenIcon) => {")
a("    const Icon = icon;")
a("    const isEditing = editing === section;")
a("    return (")
a("      <div className=\"flex items-center justify-between mb-3\">")
a("        <div className=\"flex items-center gap-2\">")
a("          <Icon className=\"w-4 h-4 text-primary\" />")
a("          <h3 className=\"font-semibold text-foreground text-sm\">{label}</h3>")
a("        " + d)
a("        <button")
a("          type=\"button\"")
a("          onClick={() => (isEditing ? saveSection(section) : setEditing(section))}")
a("          className=\"flex items-center gap-1.5 text-xs text-primary font-medium hover:underline\"")
a("        >")
a("          {isEditing ? <CheckIcon className=\"w-3.5 h-3.5\" /> : <EditIcon className=\"w-3.5 h-3.5\" />}")
a("          {isEditing ? `Save` : `Edit`}")
a("        </button>")
a("      " + d)
a("    );")
a("  };")
a("")
a("  return (")
a('    <div data-cmp="ProfilePanel" className="flex flex-col h-full">')
a('      <div className="px-6 py-4 border-b border-border bg-card shrink-0">')
a('        <div className="flex items-center gap-3">')
a('          <div className="w-9 h-9 rounded-xl bg-accent flex items-center justify-center">')
a('            <UserIcon className="w-5 h-5 text-primary" />')
a("          " + d)
a("          <div>")
a('            <h1 className="text-lg font-bold text-foreground">My Profile</h1>')
a('            <p className="text-xs text-muted-foreground">Saved to DynamoDB · Powers your recommendations</p>')
a("          " + d)
a("        " + d)
a("      " + d)
a('      <div className="flex-1 overflow-y-auto px-6 py-5 scrollbar-thin">')
a('        <div className="p-6 rounded-2xl bg-brand text-brand-foreground shadow-custom mb-6">')
a('          <div className="flex items-center gap-4 mb-4">')
a('            <div className="w-16 h-16 rounded-2xl bg-white/20 flex items-center justify-center text-3xl font-bold text-white shrink-0">')
a("              {profile.name.charAt(0)}")
a("            " + d)
a("            <div>")
a('              <h2 className="text-2xl font-bold">{profile.name}</h2>')
a('              <div className="flex items-center gap-3 mt-1 text-white/70 text-sm">')
a('                <GraduationCapIcon className="w-4 h-4" />')
a("                {getGradeLabel(profile.grade)}")
a("                <span>·</span>")
a("                <span>Age {profile.age}</span>")
a("              " + d)
a("            " + d)
a("          " + d)
a('          <div className="h-px bg-white/20 mb-4" />')
a("          [[COMPLETE_BAR]]")
a("        " + d)
a('        <div className="bg-card rounded-2xl border border-border shadow-custom p-5 mb-5">')
a("          {sectionHeader('Goals & Milestones', 'goals', TargetIcon)}")
a("          {editing === 'goals' ? (")
a('            <textarea value={editGoals} onChange={(e) => setEditGoals(e.target.value)} rows={4} className="w-full px-4 py-3 rounded-xl border border-border bg-muted text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none" />')
a("          ) : profile.goals.trim() ? (")
a('            <p className="text-sm text-muted-foreground leading-relaxed">{profile.goals}</p>')
a("          ) : (")
a("            <EmptyHint onEdit={() => setEditing('goals')} />")
a("          )}")
a("        " + d)
a('        <div className="bg-card rounded-2xl border border-border shadow-custom p-5 mb-4">')
a("          {sectionHeader('Academic Interests', 'interests', BookOpenIcon)}")
a("          {editing === 'interests' ? (")
a("            <InterestPicker selected={editInterests} onChange={setEditInterests} />")
a("          ) : profile.interests.length ? (")
a('            <div className="flex flex-wrap gap-2">')
a("              {profile.interests.map((interest) => (")
a('                <span key={interest} className="text-sm px-3 py-1 rounded-full bg-accent text-accent-foreground border border-accent-foreground/15 font-medium">{interest}</span>')
a("              ))}")
a("            " + d)
a("          ) : (")
a("            <EmptyHint onEdit={() => setEditing('interests')} />")
a("          )}")
a("        " + d)
a('        <div className="bg-card rounded-2xl border border-border shadow-custom p-5 mb-4">')
a("          {sectionHeader('Strengths', 'strengths', SparklesIcon)}")
a("          {editing === 'strengths' ? (")
a('            <textarea value={editStrengths} onChange={(e) => setEditStrengths(e.target.value)} rows={3} placeholder="Comma-separated" className="w-full px-4 py-3 rounded-xl border border-border bg-muted text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none" />')
a("          ) : profile.strengths.length ? (")
a('            <div className="flex flex-wrap gap-2">')
a("              {profile.strengths.map((s) => (")
a('                <span key={s} className="text-sm px-3 py-1 rounded-full bg-emerald-muted text-emerald border border-emerald/20 font-medium">{s}</span>')
a("              ))}")
a("            " + d)
a("          ) : (")
a("            <EmptyHint onEdit={() => setEditing('strengths')} />")
a("          )}")
a("        " + d)
a('        <div className="bg-card rounded-2xl border border-border shadow-custom p-5 mb-4">')
a("          {sectionHeader('Extracurricular Activities', 'extracurriculars', TrophyIcon)}")
a("          {editing === 'extracurriculars' ? (")
a('            <textarea value={editActivities} onChange={(e) => setEditActivities(e.target.value)} rows={4} placeholder="One per line" className="w-full px-4 py-3 rounded-xl border border-border bg-muted text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none" />')
a("          ) : profile.extracurriculars.length ? (")
a('            <div className="flex flex-col gap-2">')
a("              {profile.extracurriculars.map((activity) => (")
a("                [[ACTIVITY_ROW]]")
a("              ))}")
a("            " + d)
a("          ) : (")
a("            <EmptyHint onEdit={() => setEditing('extracurriculars')} />")
a("          )}")
a("        " + d)
a("      " + d)
a("    " + d)
a("  );")
a("}")

text = "\n".join(L)
bad = "motion" + "less" + "Overlay"
text = text.replace("<" + bad + " />", '<div className="flex items-center justify-between mb-2 text-sm"><span className="text-white/70">Profile completeness</span><span className="font-bold">{completeness}%</span></div><div className="h-2 rounded-full bg-white/20"><motionlessOverlay /></div>')
text = text.replace("<" + bad + " />", '<div className="h-full rounded-full bg-white" style={{ width: `${completeness}%` }} /></div>')
text = text.replace("<" + bad + " />", '<div key={activity} className="flex items-center gap-3 p-3 rounded-xl bg-muted border border-border"><TrophyIcon className="w-4 h-4 text-amber shrink-0" /><span className="text-sm text-foreground">{activity}</span></div>')

out.write_text(text, encoding="utf-8")
print("wrote", out)
